version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports: 
      - "5432:5432"
  
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"